CREATE TABLE [dbo].[PLANOS](
	[ID_PLANO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_PLANO] [varchar](100) NOT NULL,
	[VALOR] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_PLANOS] PRIMARY KEY CLUSTERED 
(
	[ID_PLANO] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CLIENTES](
	[ID_CLIENTE] [bigint] NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[EMAIL] [varchar](150) NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CONTRATOS](
	[ID_CONTRATO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [bigint] NOT NULL,
	[ID_PLANO] [int] NOT NULL,
	[DATA_INICIO] [date] NOT NULL,
 CONSTRAINT [PK_CONTRATOS] PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRATOS]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATOS_CLIENTES] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTES] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[CONTRATOS]  WITH CHECK ADD  CONSTRAINT [FK_CONTRATOS_PLANOS] FOREIGN KEY([ID_PLANO])
REFERENCES [dbo].[PLANOS] ([ID_PLANO])
GO